name: Create Archive
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release Folder
      run:  rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./moodle-enrol_invitation
    - name: Switch to Release Folder
      run: cd moodle-enrol_invitation
    - uses: actions/checkout@master
    - name: Switch back
      run: cd ..
    - name: Archive Release
      run: zip -r /moodle-enrol_invitation.zip . -x ".git/*" ".github/*"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'moodle-enrol_invitation.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        commit: master
        tag: v1.0.${{ github.run_number }}
