name: Create Archive
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'moodle-enrol_invitation.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: 'moodle-enrol_invitation.zip'
        
